version: "3.9"

networks:
  economic-network:

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - economic-network
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=economic_school
    networks:
      - economic-network
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/economic_school?sslmode=disable
    depends_on:
      - postgres
      - redis
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
    networks:
      - economic-network
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@example.com
#      - PGADMIN_DEFAULT_PASSWORD=keita551201
#      - PGADMIN_DISABLE_POSTFIX_LOGGING=true
#      - PGADMIN_DISABLE_SETTINGS_ACCESS_LOG=true
#      - PGADMIN_DISABLE_BROWSER_ACCESS_LOG=true
#    ports:
#      - "5050:80"
#    networks:
#      - economic-network
#    depends_on:
#      - postgres
#    volumes:
#      - ./pgadmin:/pgadmin
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data
    volumes:
      - minio-data:/data
    logging:
      driver: none
    networks:
      - economic-network
volumes:
  minio-data:
    driver: local



