// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailLog struct {
	ID          int64         `json:"id"`
	Email       string        `json:"email"`
	BounceCount sql.NullInt32 `json:"bounce_count"`
	CreatedAt   time.Time     `json:"created_at"`
}

type Exam struct {
	ExamID         int32          `json:"exam_id"`
	University     string         `json:"university"`
	Subject        string         `json:"subject"`
	Year           int32          `json:"year"`
	QuestionNum    int32          `json:"question_num"`
	QuestionPdfUrl sql.NullString `json:"question_pdf_url"`
	AnswerPdfUrl   sql.NullString `json:"answer_pdf_url"`
	VideoUrl       sql.NullString `json:"video_url"`
	CritiqueUrl    sql.NullString `json:"critique_url"`
	CreatedAt      time.Time      `json:"created_at"`
}

type GlobalRanking struct {
	Username          string    `json:"username"`
	NumCompletedExams int32     `json:"num_completed_exams"`
	RankingDate       string    `json:"ranking_date"`
	CreatedAt         time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type UniversityRanking struct {
	Username          string    `json:"username"`
	University        string    `json:"university"`
	NumCompletedExams int32     `json:"num_completed_exams"`
	RankingDate       string    `json:"ranking_date"`
	CreatedAt         time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	UserType          int32     `json:"user_type"`
	ProfileImageUrl   string    `json:"profile_image_url"`
	IsEmailVerified   bool      `json:"is_email_verified"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	Version           int32     `json:"version"`
}

type UserExam struct {
	Username    string       `json:"username"`
	ExamID      int32        `json:"exam_id"`
	University  string       `json:"university"`
	IsCompleted bool         `json:"is_completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}

type WeeklyGlobalRanking struct {
	Username            string    `json:"username"`
	CompletedExamsCount int32     `json:"completed_exams_count"`
	RankingDate         string    `json:"ranking_date"`
	CreatedAt           time.Time `json:"created_at"`
}

type WeeklyUniversityRanking struct {
	Username            string    `json:"username"`
	University          string    `json:"university"`
	CompletedExamsCount int32     `json:"completed_exams_count"`
	RankingDate         string    `json:"ranking_date"`
	CreatedAt           time.Time `json:"created_at"`
}
